image: timbru31/ruby-node:latest

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - npm install
  - npm run build
  - gem install bundler
  - bundle install

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  script:
  - bundle exec jekyll build --config _config.yml,./configs/_${CI_COMMIT_REF_NAME}.yml -d public 
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == "master" ||  $CI_COMMIT_REF_NAME == "develop"
