name: Deploy Site

on:
  push:
    branches:
      - main  # or your default branch

env: 
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ~=24.1.0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"

      - name: Install dependencies
        run: |
          npm install
          gem install bundler
          bundle install

      - name: Build site
        run: |
          npm run build
          bundle exec jekyll build --config _config.yml -d public

      - name: Deploy to GitHub Pages
        if: github.ref == ${{ github.event.repository.default_branch }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
